[build]
baseImage = "python:3.10"

[phases]
setup = [
    "python -m venv /opt/venv",
    "mkdir -p /opt/venv/pip-cache"
]

install = [
    ". /opt/venv/bin/activate",
    "pip install --cache-dir /opt/venv/pip-cache --upgrade pip",
    "pip install --cache-dir /opt/venv/pip-cache -r requirements.txt"
]

build = [
    ". /opt/venv/bin/activate",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "/opt/venv/bin/gunicorn listings_project.wsgi:application --bind 0.0.0.0:$PORT"