[build]
baseImage = "python:3.10"

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn listings_project.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
