[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "libpqxx"  # Needed for PostgreSQL (psycopg2)
]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn listings_project.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
