[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "python311Packages.psycopg2-binary"  # Optional if needed separately
]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput --settings=listings_project.settings.production",
  "python manage.py migrate --settings=listings_project.settings.production"
]

[start]
cmd = "gunicorn listings_project.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
