[phases.setup]
nixPkgs = [
  "python311",              # Install Python 3.11 via Nix
  "python3Packages.pip",    # Install pip via Nix (included in python3Packages)
  "python3Packages.setuptools" # Install setuptools
]

[phases.install]
cmds = [
  "pip install -r requirements.txt"  # Now we use pip as provided by Nix
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn listings_project.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
