[phases.setup]
nixPkgs = [
  "python311",              # Install Python 3.11
  "python3Packages.pip",    # Ensure pip is available via Nix
  "python3Packages.setuptools"  # Install setuptools (if required)
]

[phases.install]
cmds = [
  "pip install -r requirements.txt"  # Use the pip that comes with Python via Nix
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn listings_project.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
